### ISSUE TITLE
Fix error according autoload of the files in the "routes" folder

### ISSUE THREAD

**Issue by danielsteuri** [flowingones/cargo#1]
Path handling of the `loadRoutes` function does not work as expected. The following error is throw:

```
TypeError: The module's source code could not be parsed: Expected ';', '}' or <eof> at https://deno.land/Users/{username}/{ProjectPath}/Cargo/tests/routes/index.ts:1:11
    at async loadRoutes (https://deno.land/x/cargo@0.1.0/core/routing/file-loader.ts:9:9)
    at async bootstrap (https://deno.land/x/cargo@0.1.0/core/app.ts:15:8)
    at async file:///Users/{username}/{ProjectPath}/Cargo/tests/main.ts:3:13```

**Comment by danielsteuri** [comment]
Fixed in `7b1afafb14d6b850217a6bf1a7441f3ba2956b99`
